import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const apercuPro = localFont({
  src: './font/Apercu Pro/apercu_regular_pro.otf'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${apercuPro.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
